common/models/Page.php
<?php

namespace common\models;

use Yii;
use common\components\helpers\Setup;

/**
 * This is the model class for table "{{%pages}}".
 *
 * @property integer $id
 * @property integer $status
 * @property integer $priority
 * @property integer $page_robot_indexing
 * @property string $url_name
 * @property string $title
 * @property string $h1_tag
 * @property string $body
 * @property string $menu_label
 * @property string $show_contact_form
 * @property string $show_testimonial
 * @property string $additional_text
 * @property string $meta_keywords
 * @property string $meta_description
 * @property integer $page_type_id
 * @property integer $page_category_id
 * @property integer $page_template_id
 * @property integer $parent_id
 * @property integer $view_counter
 * @property integer $menu_type
 * @property string $video_link
 * @property integer $related_media_id
 * @property integer $publication_date
 * @property integer $creator_id
 * @property integer $created_at
 * @property integer $updater_id
 * @property integer $updated_at
 *
 * @property User $creator
 * @property User $updater
 * @property PageTypes $pageType
 */
class Page extends \common\components\classes\BackendActiveRecord{

  const PAGE_COMMON     = 1;
  const PAGE_PROPERTIES = 2;
  const PAGE_BLOG       = 3;
  const PAGE_AGENCY     = 4;
  const PAGE_ACCOUNT    = 5;


  /**
   * @inheritdoc
   */
  public static function tableName(){
    return '{{%pages}}';
  }

  /**
   * @inheritdoc
   */
  public function rules(){
    return [
      [['status', 'priority', 'page_type_id', 'page_category_id', 'page_template_id', 'parent_id',
        'view_counter', 'menu_type', 'related_media_id', 'creator_id', 'created_at',
        'updater_id', 'updated_at', 'page_robot_indexing', 'show_contact_form', 'show_testimonial'], 'integer'],
      [['title'], 'required'],
      [['url_name'], 'required', 'on' => 'page-update'],
      [['h1_tag'], 'required', 'on' => 'page-with-header'],
      [['body', 'additional_text'], 'string'],
      [['url_name', 'title', 'h1_tag', 'menu_label', 'meta_keywords'], 'string', 'max' => 255],
      [['meta_description', 'video_link'], 'string', 'max' => 1024],
      [['show_contact_form', 'show_testimonial'], 'default', 'value' => self::STATUS_DRAFT],
      ['menu_label', 'required', 'when' => function($model) {return $model->menu_type === 1;}
        , 'whenClient' => "function (attribute, value) {return $('#page-menu_type').val() == 1;}"
        ,'message' => Yii::t('app','Please add menu label')],
    ];
  }

  /**
   * @inheritdoc
   */
  public function attributeLabels(){
    return [
      'id' => Yii::t('app', 'ID'),
      'status' => Yii::t('app', 'Active ?'),
      'page_robot_indexing' => Yii::t('app', 'Index by search engines ?'),
      'priority' => Yii::t('app', 'Priority'),
      'url_name' => Yii::t('app', 'Slug Name'),
      'show_contact_form' => Yii::t('app', 'Show contact form in current page'),
      'show_testimonial' => Yii::t('app', 'Show testimonial in current page'),
      'title' => Yii::t('app', 'Title'),
      'h1_tag' => Yii::t('app', 'Page header'),
      'body' => Yii::t('app', 'Body'),
      'additional_text' => Yii::t('app', 'Additional field'),
      'meta_keywords' => Yii::t('app', 'Meta Keywords'),
      'meta_description' => Yii::t('app', 'Meta Description'),
      'page_type_id' => Yii::t('app', 'Page Type'),
      'page_category_id' => Yii::t('app', 'Page Category'),
      'page_template_id' => Yii::t('app', 'Page Template'),
      'parent_id' => Yii::t('app', 'Parent Page In Navigation Menu'),
      'view_counter' => Yii::t('app', 'Views'),
      'menu_type' => Yii::t('app', 'Menu Type'),
      'video_link' => Yii::t('app', 'Video Link'),
      'related_media_id' => Yii::t('app', 'Related Media'),
      'publication_date' => Yii::t('app', 'Publication Date'),
      'creator_id' => Yii::t('app', 'Creator'),
      'created_at' => Yii::t('app', 'Created At'),
      'updater_id' => Yii::t('app', 'Updater'),
      'updated_at' => Yii::t('app', 'Updated At'),
    ];
  }

  /**
   * @return \yii\db\ActiveQuery
   */
  public function getImage(){
    return \common\models\MediaStorage::find()->where(['model_id' => $this->id])
      ->andWhere(['model' => 'Page'])->andWhere(['default' => 1])->one();
  }

  /**
   * @return \yii\db\ActiveQuery
   */
  public function getWithImages(){
    return $this->hasMany(MediaStorage::className(), ['model_id' => 'id'])
      ->andWhere(['model' => 'Page']);
  }

  /**
   * @return \yii\db\ActiveQuery
   */
  public function getCreator(){
    return $this->hasOne(User::className(), ['id' => 'creator_id']);
  }

  /**
   * @return \yii\db\ActiveQuery
   */
  public function getUpdater(){
    return $this->hasOne(User::className(), ['id' => 'updater_id']);
  }

  /**
   * @return \yii\db\ActiveQuery
   */
  public function getPageType(){
    return $this->hasOne(PageTypes::className(), ['id' => 'page_type_id']);
  }

  /**
   * @return \yii\db\ActiveQuery
   */
  public function getParent(){
    return $this->hasOne(self::className(), ['id' => 'parent_id']);
  }

  /**
   * @return \yii\db\ActiveQuery
   */
  public function getCategory(){
    return $this->hasOne(PageCategory::className(), ['id' => 'page_category_id']);
  }

  /**
   * For all pages create url
   * @param bool $insert
   * @return bool
   */
  public function beforeSave($insert){
    if(empty($this->parent_id)) $this->parent_id = 1;

    if($this->page_template_id !== 5)
      $this->url_name = Setup::generateUniqueUrl($this);

    if (parent::beforeSave($insert)){
      return true;
    } else {
      return true;
    }
  }

  /**
   * @return array
   */
  public function menuPosition(){
    $output = [
      0 => Yii::t('app', 'Not in menu'),
      1 => Yii::t('app', 'In menu'),
      2 => Yii::t('app', 'In menu (Only Link)'),
    ];
    return $output;
  }


  public function pageTemplate(){
    return [
      self::PAGE_COMMON => 'Common Pages',
      self::PAGE_PROPERTIES => 'Properties',
      self::PAGE_BLOG => 'Blog Page',
    ];
  }

}

backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use common\components\keyStorage\FormModel;
use Yii;

/**
 * Site controller
 */
class SiteController extends \common\components\classes\BackendController{
  /**
   * @inheritdoc
   */
  public function actions(){
    return [
      'error' => [
        'class' => 'yii\web\ErrorAction',
      ]
    ];
  }

  public function beforeAction($action){
    $this->layout = Yii::$app->user->isGuest ? 'base' : 'common';
    return parent::beforeAction($action);
  }

  public function actionSettings(){
      $model = new FormModel([
          'keys' => [
              'frontend.maintenance' => [
                  'label' => Yii::t('backend', 'Frontend maintenance mode'),
                  'type' => FormModel::TYPE_DROPDOWN,
                  'items' => [
                      'disabled' => Yii::t('backend', 'Disabled'),
                      'enabled' => Yii::t('backend', 'Enabled')
                  ]
              ],
              'backend.theme-skin' => [
                  'label' => Yii::t('backend', 'Backend theme'),
                  'type' => FormModel::TYPE_DROPDOWN,
                  'items' => [
                      'skin-black' => 'skin-black',
                      'skin-blue' => 'skin-blue',
                      'skin-green' => 'skin-green',
                      'skin-purple' => 'skin-purple',
                      'skin-red' => 'skin-red',
                      'skin-yellow' => 'skin-yellow'
                  ]
              ],
              'backend.layout-fixed' => [
                  'label' => Yii::t('backend', 'Fixed backend layout'),
                  'type' => FormModel::TYPE_CHECKBOX
              ],
              'backend.layout-boxed' => [
                  'label' => Yii::t('backend', 'Boxed backend layout'),
                  'type' => FormModel::TYPE_CHECKBOX
              ],
              'backend.layout-collapsed-sidebar' => [
                  'label' => Yii::t('backend', 'Backend sidebar collapsed'),
                  'type' => FormModel::TYPE_CHECKBOX
              ]
          ]
      ]);

      if ($model->load(Yii::$app->request->post()) && $model->save()) {
        Yii::$app->session->setFlash('alert', [
          'body' => Yii::t('backend', 'Settings was successfully saved'),
          'options' => ['class' => 'alert alert-success']
        ]);
        return $this->refresh();
      }

      return $this->render('settings', ['model' => $model]);
  }
}

frontend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;
use yii\helpers\Url;

$this->title = $name;
$this->registerMetaTag(['name' => 'robots', 'content' => 'noindex,follow']);

?>


<div class="container" style="min-height: 500px;">
  <div class="content">
    <div class="not-found">
      <div class="not-found-title text-center">
        <strong>404</strong> <span><?= Yii::t('frontend', 'Page not found') ?></span>
      </div>

      <div class="not-found-content">
        <h1 class="not-found-subtitle"><?= yii::t('common', 'You have several options') ?></h1>

        <div class="row">
          <div class="col-sm-5">
            <ul class="not-found-list">
              <li><?= Yii::t('common', 'Return back to <a href="{link}">homepage</a>', ['link' => Url::to(['/'])]) ?></li>
              <li><?= Yii::t('common', 'Check our most recent <a href="{link}">properties</a>', ['link' => Url::to(['/property/index'])]) ?></li>
              <li><?= Yii::t('common', 'Contact us via our contact details, shown in footer.') ?></li>
            </ul>
          </div><!-- /.col-* -->

          <div class="col-sm-7">
          </div><!-- /.col-* -->
        </div><!-- /.row -->
      </div><!-- /.not-found-content -->
    </div>
  </div><!-- /.content -->
</div><!-- /.container -->

frontend/views/site/index.php
<?php
/* @var $this yii\web\View */
/* @var $site common\models\Page */
/* @var $about common\models\Page */
/* @var $featured_properties common\models\Property */
/* @var $map_properties common\models\Property */
/* @var $featured_agencies common\models\Agency */
/* @var $state common\models\State */
/* @var $testimonials common\models\Page */

use yii\helpers\Url;
use common\components\helpers\Setup;
use yii\helpers\ArrayHelper;



$this->title = $site['title'];

$this->registerMetaTag(['name' => 'keywords', 'content' => $site['meta_keywords']]);
$this->registerMetaTag(['name' => 'description', 'content' => $site['meta_description']]);
if(!$site['page_robot_indexing'])
  $this->registerMetaTag(['name' => 'robots', 'content' => 'noindex,follow']);

$storage = Yii::getAlias('@storageUrl');


$js = <<<'SCRIPT'

var isIOS = /iPad|iPhone|iPod/.test(navigator.platform);
if (isIOS) {
  var canvasVideo = new CanvasVideoPlayer({
    videoSelector: '.video',
    canvasSelector: '.canvas',
    timelineSelector: false,
    autoplay: true,
    makeLoop: true,
    pauseOnClick: false,
    audio: false
  });
} else {
  // Use HTML5 video
  $('.canvas').hide();
  //document.querySelectorAll('.canvas')[0].style.display = 'none';
}

SCRIPT;

$this->title = $site['title'];

$this->registerJs($js);
$this->registerJsFile("/assets/production/js/canvas-video-player.min.js");

?>

<script>
  var youtube_code = '<?= $about->video_link ?>' ;
  var video_image = '<?= !empty($media = $about->image) ? $storage.$media->media_path : '' ?>';
</script>
<style>

</style>

<!-- Home On Image Section
---------------------------------------------------------------------->
<?php
$js = <<< 'SCRIPT'
$(document).ready(function(){
$('video').html('<source src="/img/video/home.mp4" type="video/mp4">'+
      '<source src="/img/video/home.ogv" type="video/ogg">'+
      '<source src="/img/video/home.webm" type="video/webm">'+
      'Your browser doesn\'t support HTML5 video. Here\'s a <a href="/img/video/home.mp4">link</a> to download the video.');
});
SCRIPT;
$this->registerJs($js);
?>

<section id="home" data-type="background" data-speed="10">
  <div id="video-wrapper">
    <video class="video" muted="muted" loop="loop" autoplay="autoplay" poster="/img/video/background.jpg">
<!--      <source src="/img/video/home.mp4" type="video/mp4">-->
<!--      <source src="/img/video/home.ogv" type="video/ogg">-->
<!--      <source src="/img/video/home.webm" type="video/webm">-->
<!--      Your browser doesn't support HTML5 video. Here's a <a href="/img/video/home.mp4">link</a> to download the video.-->
    </video>
  </div>
  <div id="home-page-header-container-wrapper">
    <div id="home-page-header-container">
      <div class="container">
        <div class="row">
          <div class="col-sm-12 text-center">
            <h3 class="slogan">Permit approved and permit potential</h3>
            <h1 class="text-center introduction-header h1">
              <?= $site['h1_tag']?>
            </h1>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container -->
    </div><!-- /#home-page-header-container -->
    <div id="home-page-header-bottom-container">
      <div id="header-search-box-container">
        <?= \frontend\widgets\SearchBar::widget(); ?>
      </div><!-- /#header-search-box-container -->
    </div>
  </div>
</section>

<!-- MAP SECTION
---------------------------------------------------------------------->
<section id="map-section">
  <div class="container">
    <div class="map-open-button-box-container row">
      <div class="col-sm-2 col-sm-offset-5 map-open-button-box-block">
        <p class="text-center">
          <span class="ci ci-map"></span><span class="map-text">Map</span><span id="open-map" class="ci ci-arrow-down closed"></span>
        </p>
      </div>
    </div>
  </div>
</section>

<?= $this->render("//layouts/parts/_map", ['state' => $state, 'properties' => $map_properties]) ?>

<!-- FEATURED PROPERTIES
---------------------------------------------------------------------->
<section id="featured-properties">
  <div class="container">
    <div class="row">
      <div style="margin-top: 25px;">&nbsp;</div>
      <h2 class="page-header text-left col-xs-12"><span>Featured</span> Development Sites</h2>
    </div><!--/.row-->
    <div id="property-carousel">
      <?= $this->render("//layouts/parts/_properties_carousel", ['properties' => $featured_properties, 'storage' => $storage]) ?>
    </div> <!--/#property-carousel-->
  </div><!--/.container-->
</section><!--section ends-->

<!-- AGENCIES LOGOs
---------------------------------------------------------------------->
<section id="agencies-logos">
  <div class="container">
    <div class="row">
      <h2 class="page-header text-left col-xs-12"><span>TRUSTED</span> by</h2>
    </div><!--/.row-->
    <div class="row">
      <div class="col-sm-12 col-md-8">
        <?= $this->render("//layouts/parts/_slider", ['agencies' => $featured_agencies]) ?>
        <div class="clearfix"></div>
      </div>
      <div class="col-sm-12 col-md-4">
        <!--           <script type="text/javascript" src="http://permitready.com.au/assets/widgets/widget.js?v=1.0"></script> -->
        <!--class="google-square-banner banner"-->
        <!-- /36639447/Homepage_logo_square -->
        <div id='div-gpt-ad-1456820027687-2' style='height:280px; width:336px;'>
          <script type='text/javascript'>
            googletag.cmd.push(function() { googletag.display('div-gpt-ad-1456820027687-2'); });
          </script>
        </div>
      </div>
    </div><!--/.row-->
  </div><!--/.container-->
</section><!--section ends-->

<!-- Separator
---------------------------------------------------------------------->
<hr class="section-separator"/>

<!-- LATEST LISTINGS
---------------------------------------------------------------------->
<section id="latest-properties">
  <div class="container">
    <div class="row">
      <h2 class="page-header text-left col-xs-12"><span>Latest</span> Listings</h2>
    </div><!--/.row-->
    <div id="latest-carousel">
      <?= $this->render("//layouts/parts/_properties_carousel", ['properties' => $latest_properties, 'storage' => $storage]) ?>
    </div> <!--/#property-carousel-->
  </div><!--/.container-->
</section><!--section ends-->

<!-- SECTION BLOG
---------------------------------------------------------------------->
<section id="home-page-blog-section">
  <div class="container">
    <div id="home-page-blog-header" class="row">
      <div class="col-lg-8 col-md-12 pull-right text-right">
        <!-- /36639447/Homepage_Industry_News -->
        <div class="width-banner" id='div-gpt-ad-1460360910375-0' style='height:90px; width:728px;'>
          <script type='text/javascript'>
            googletag.cmd.push(function() { googletag.display('div-gpt-ad-1460360910375-0'); });
          </script>
        </div>
      </div>
      <div class="col-lg-4 col-md-12">
        <h2 class="page-header"><span>industry</span> news</h2>
      </div>
    </div>
    <div id="home-page-blog-news" class="row">
      <?php foreach($blog as $item): ?>
        <?php if(!empty($image = $item->image)): ?>
          <?php $blog_url = Url::to(["/{$item->url_name}"]); $date = $item->publication_date ?>
          <div class="col-sm-6">
            <div class="home-page-blog-news-block">
              <div class="content-image col-sm-6">
                <a href="<?= $blog_url ?>">
                  <img data-src="<?= $storage.$image->media_path ?>"/>
                  <div class="content-image-overlay">
                    <dl>
                      <dt><?= date('d', $date) ?></dt>
                      <hr/>
                      <dt><?= date('M', $date) ?></dt>
                    </dl>
                  </div>
                </a>
              </div>
              <div class="content-description col-sm-6">
                <h5 class="content-header text-center"><?= $item->h1_tag ?></h5>
                <hr/>
                <p class="content-text">
                  <?= Setup::truncate($item->body, '120', '...') ?>
                </p>
                <p class="read-more-block text-right">
                  <a href="<?= $blog_url ?>" class="read-more">Read more</a>
                </p>
              </div>
            </div>
          </div><!--/.col-->
        <?php endif; ?>
      <?php endforeach; ?>
    </div><!--/.row-->
    <div class="row">
      <div class="col-sm-4 col-sm-offset-4 text-center margin-top-20">
        <a href="<?= Url::to(["/blog"]) ?>" class="btn brand-green btn-read-more">Read More</a>
      </div>
    </div>
  </div><!--/.container-->
</section><!--section ends-->

<!-- Separator
---------------------------------------------------------------------->
<hr class="section-separator"/>


<!-- ABOUT PREVIEW NAME
---------------------------------------------------------------------->
<section id="about-preview">
  <div class="container">
    <div id="about-preview" class="col-sm-10">
      <div class="row">
        <div class="col-sm-12">
          <h2 class="page-header"><?= $about->h1_tag ?></h2>
        </div>
      </div><!--/.row-->
      <div class="row">
        <div class="col-sm-12">
          <div class="row">
            <div class="col-sm-6" style="padding-left: 0">
              <div id="about-video"></div>
              <div id="thumbnail_container" class="thumbnail_container embed-responsive embed-responsive-16by9">
                <img class="thumbnail" id="video-thumbnail" />
              </div>
              <a class="ci start-video"></a>
            </div>
            <div class="col-sm-6">
              <div class="content-title">
                <div class="content-description">
                  <?= Setup::truncate($about->body, 900, '...') ?>
                </div>
                <a href="/page/about" class="btn brand-green btn-read-more">Read more</a>
              </div>
            </div>
          </div><!--/.row-->
        </div><!--/.col-->
      </div><!--/.row-->
    </div>
    <div class="col-sm-2">
      <!-- /36639447/hompage_skyscraper -->
      <div id='div-gpt-ad-1456820027687-3' style='height:600px; width:120px;'>
        <script type='text/javascript'>
          googletag.cmd.push(function() { googletag.display('div-gpt-ad-1456820027687-3'); });
        </script>
      </div>
    </div>
  </div>
</section>


<!-- TESTIMONIAL SECTION
---------------------------------------------------------------------->
<section id="testimonials">
  <div class="container">
    <div class="row">
      <h2 class="page-header text-left col-xs-12"><span>What </span>leading agents are saying</h2>
    </div><!--/.row-->
    <div id="testimonials-carousel" class="text-center">
      <?php foreach($testimonials as $testimonial): ?>
        <?php if(strlen($testimonial->body) > 5): ?>
          <div>
            <div class="review-style"><?php echo $testimonial->body ?></div>
            <p class="testimonial"><strong><?= $testimonial->title ?></strong> - <?= $testimonial->h1_tag ?></strong></p>
            <p><strong><?= $testimonial->menu_label ?></strong></p>
          </div>
        <?php endif; ?>
      <?php endforeach ?>
    </div> <!--/#property-carousel-->
  </div><!--/.container-->
</section>
<!--sections ends-->

frontend/views/site/testimonials.php
<?php
/**
 * Created by PhpStorm.
 * User: aliyev.resad@gmail.com Rashad Aliyev
 * Date: 11/24/15
 * Time: 01:12
 */

use yii\helpers\Url;

$this->title = $model->title;

$this->registerMetaTag(['name' => 'keywords', 'content' => $model->meta_keywords]);
$this->registerMetaTag(['name' => 'description', 'content' => $model->meta_description]);

$storage = \Yii::getAlias('@storageUrl');
if(!empty($media = $model->image)){$image = $media->media_path;};


$js = <<< 'SCRIPT'
  $('#property-carousel').owlCarousel({
    loop:true, margin:50, nav:false, navText: ['',''], dots : false,
    responsive:{0:{items:1},600:{items:3},1000:{items:5}}
  })
SCRIPT;
$this->registerJs($js);

?>

<!-- WHY WE HEADER SECTION
---------------------------------------------------------------------->
<section id="page-why-we-header-section">
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <h1 class="page-header text-left"><?= $model->h1_tag ?></h1>
      </div>
    </div><!--/.row-->
  </div><!--/.container-->
</section><!--section ends-->

<!-- Separator
---------------------------------------------------------------------->
<hr class="section-separator"/>

<!-- Why We Body Section
---------------------------------------------------------------------->
<section id="why-we-body-section">
  <div class="container">
    <?php foreach($testimonials as $testimonial): ?>
      <div class="row">
        <div class="col-sm-12 text-center">
          <span class="ci ci-quote-orange"></span>
          <p><?= $testimonial->body ?></p>
          <h5><?= $testimonial->title ?></h5>
          <p class="small"> <?= $testimonial->h1_tag ?> <br/> <?= $testimonial->menu_label ?></p>
        </div>
      </div><!--/.row-->
    <?php endforeach; ?>
  </div><!--/.container-->
</section><!--section ends-->

<!-- Separator
---------------------------------------------------------------------->
<hr class="section-separator"/>


<!-- SECTION NAME
---------------------------------------------------------------------->
<section id="agencies">
  <div class="container">
    <div class="row">
      <h2 class="page-header col-sm-12"><span>Trusted</span> By</h2>
    </div><!--/.row-->
    <div class="row">
      <div id="property-carousel" class="trusted-logos">
        <?php foreach($agencies as $agency): ?>
          <?php if(!empty($image = $agency->image)): ?>
          <div class="logo-frame">
            <a href="<?= Url::to(["/agency/{$agency->id}"]) ?>">
              <img src="<?= $storage.$image->media_path ?>">
            </a>
          </div>
          <?php endif; ?>
        <?php endforeach; ?>
      </div>
    </div><!--/.row-->
  </div><!--/.container-->
</section><!--section ends-->